### ISSUE TITLE
navigationOptions.headerStyle not applied to stack navigator header.

### ISSUE THREAD

**Issue by ollexjr** [benevbright/react-navigation-collapsible#107]
## Information
- react-native version: 0.61.5
- react-navigation version: 4.0.10
- react-navigation-collapsible version: 3
- Platform (iOS/Android): android
- react-native init or Expo: react-native init

package.json...
"react-native-screens": "^2.0.0-alpha.22",
"react": "16.9.0",
"react-native": "0.61.5",
"react-navigation": "^4.0.10"
"react-navigation-drawer": "^2.3.3"
"react-navigation-stack": "^2.0.1"
"react-navigation-tabs": "^2.6.2"

## Detail

For some reason, the headerStyle for a stack screen, is not applied to the collapsible header component.
Could this be to do with deprecated styling options in react-navigation-stack.

**Comment by benevbright** [comment]
I just updated `react-navigation-stack` on `/example` and I can see the problem. 
Thanks for reporting.

**Comment by benevbright** [comment]
Hi, too many things changed on `react-navigation-stack@v2`. 
I'm afraid I have to ask you to use `react-navigation-stack@v1`. https://reactnavigation.org/docs/en/stack-navigator-1.0.html

Or try this new `v5` https://github.com/benevbright/react-navigation-collapsible/tree/v5

**Comment by ollexjr** [comment]
Gotcha, I've made a temporary fix to use the iOS collapsible component parameter on android but it's not a perfect solution.

I'll take a look at seeing if I can integrate v5 into my project.
