### ISSUE TITLE
inputRange error on web

### ISSUE THREAD

**Issue by RWOverdijk** [benevbright/react-navigation-collapsible#114]
![image](https://user-images.githubusercontent.com/781745/77225946-58e4f600-6b74-11ea-8d7d-d3dc0cbaaf6e.png)

## Information
- react-native version: .. https://github.com/expo/react-native/archive/sdk-36.0.0.tar.gz 😄
- react-navigation version: see below
- react-navigation-collapsible version: Master
- Platform (iOS/Android): Web
- react-native init or Expo: Expo

    "@react-navigation/bottom-tabs": "^5.0.0",
    "@react-navigation/native": "^5.0.0",
    "@react-navigation/stack": "^5.0.0",
    "@react-navigation/web": "~1.0.0-alpha.9",

## Detail

All I did was change my navigation file to this:

```jsx
import * as React from 'react'
import { createCollapsibleStack } from 'react-navigation-collapsible'
import { createStackNavigator } from '@react-navigation/stack'
import { VenuesScreen, VenueDetailsScreen } from '../screens'

const MainNavigationStack = createStackNavigator();

export const AppNavigation = () => {
  return (
    <MainNavigationStack.Navigator>

      <MainNavigationStack.Screen name="Venues" component={VenuesScreen} />
      {createCollapsibleStack(
        <MainNavigationStack.Screen name="VenueDetails" component={VenueDetailsScreen} options={{ title: '' }} />
      )}
    </MainNavigationStack.Navigator>
  )
}
```

And then running it in web. I didn't test it on a physical device.

**Comment by marioaks** [comment]
Getting the same error. Would be really great if someone could look into this!
