### ISSUE TITLE
collapsedColor with translucent statusBar

### ISSUE THREAD

**Issue by cafistro** [benevbright/react-navigation-collapsible#116]
My Screen has a 
    <StatusBar 
        ...
        translucent 
        backgroundColor="transparent"
    />.
If I add the "collapsedColor" property 
            <Stack.Screen 
              ...
            />,
            {
              collapsedColor: 'white'
            }
the statusbar will be white - always. 
Am I missing something?
Is there any event i could hook into, so i was able to change the color myself?
Maybe I can pass my StatusBar into somewhere?

Thanks in advance

**Comment by benevbright** [comment]
Hi, @cafistro Thanks for your issue.
Could you provide a gif or a screenshot?

**Comment by cafistro** [comment]
Hello, 
sorry it took me so long.
below is a more detailed screenshot. 
1: Header without "collapsedColor" property.
2: with "collapsedColor" property.

a: collapsed
b: expanded

What I am looking for is a Header with states 1a & 2b.

Thanks for your time

![collapsibleHeader](https://user-images.githubusercontent.com/10344087/78255605-cfc8aa00-74f7-11ea-89d0-e12f3cb9d32f.jpg)

**Comment by benevbright** [comment]
@cafistro Thank a lot for your information. I will take a look.

**Comment by benevbright** [comment]
Hi, @cafistro 
There was a problem when using custom `headerStyle.height`. https://github.com/benevbright/react-navigation-collapsible/pull/130 This PR fixed it. 

I will fix the status problem soon and release them together.

**Comment by benevbright** [comment]
`v5.6.0` includes #130.
