### ISSUE TITLE
Extra Header (Search Bar) Is there anyway to have the search initially hidden?

### ISSUE THREAD

**Issue by hwhh** [benevbright/react-navigation-collapsible#132]
Hi, 

First off wanted to say thank you for the great library! 

I am currently using version 3.0.3 and was have more or less copied the extra header search (search bar) example. However I was wondering, is there any way to have the search initially hidden? I am trying to achieve the bellow effect:

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/17745809/81497653-aef23200-92b7-11ea-86d3-f285c348bdff.gif)

**Comment by benevbright** [comment]
Hi, @hwhh Thanks for the issue. I see what you mean. 
But sadly, it won't be possible..
