### ISSUE TITLE
Ghost Click on headerRight Stack Navigator

### ISSUE THREAD

**Issue by DragonBoyX** [benevbright/react-navigation-collapsible#135]
I implemented the React Navigation Collapsible as per the documentation. Further I had to use headerRight from React Navigation V5 to place a button on the right of the Stack Navigator. 

*Now the Problem Case*
First of all the Collapsible functionality is working flawlessly. The issue occurs in this scenario -

Step 1 - Scrolling up hides the navigator
Step 2 - Scrolling down reveals the collapsed navigator
Step 3 - Now consider that I'm half the way through my feed and I scroll down to reveal the header. Now when I click on the header right button it executes the onPress like it should. Although a card which is right behind the navigator is also ghost clicked.

The problem is solved when I remove the collapsible functionality. It occurs only with the collapsible. 

Brother, can you guide me on how I can overcome this issue?

**Comment by benevbright** [comment]
Hi, Thanks for the issue. 

This is because `react-navigation`'s `headerBackground` doesn't swallow the touch event but just pass it down to the next element. 
https://github.com/benevbright/react-navigation-collapsible/blob/51b3da7ded17c2942ef52f212d15c58fa0658eb6/src/createCollapsibleStack.tsx#L132

I will report it to `react-navigation` or open PR there. 

Does it happen always even if you click your right button correctly or it happens sometimes when you miss clicks? I'm asking it because your button component at least should swallow the touch event.

**Comment by benevbright** [comment]
It looks like this one is the related one. https://github.com/react-navigation/react-navigation/issues/7102

**Comment by DragonBoyX** [comment]
> Hi, Thanks for the issue. 
> 
> This is because `react-navigation`'s `headerBackground` doesn't swallow the touch event but just pass it down to the next element. 
> https://github.com/benevbright/react-navigation-collapsible/blob/51b3da7ded17c2942ef52f212d15c58fa0658eb6/src/createCollapsibleStack.tsx#L132
> 
> I will report it to `react-navigation` or open PR there. 
> 
> Does it happen always even if you click your right button correctly or it happens sometimes when you miss clicks? I'm asking it because your button component at least should swallow the touch event. 

Hey!
Thanks for the quick reply mate. I'll go through the reference.

Yes, it does happen everytime I click on the headerRight button. To further add on to the case, both the HeaderButton onPress event and the card's (that's behind the navigation) onPress event both simultaneously gets processed.

**Comment by benevbright** [comment]
Thanks for more information.

![May-23-2020 09-31-01](https://user-images.githubusercontent.com/916690/82724703-37210000-9cd8-11ea-8421-df1a8b496264.gif)

And I just tested the latest example of `react-navigation` and can see it.

**Comment by DragonBoyX** [comment]
> Thanks for more information.
> 
> ![May-23-2020 09-31-01](https://user-images.githubusercontent.com/916690/82724703-37210000-9cd8-11ea-8421-df1a8b496264.gif)
> 
> And I just tested the latest example of `react-navigation` and can see it.

Sure mate! Let me know if this gets solved.

**Comment by benevbright** [comment]
https://github.com/react-navigation/react-navigation/pull/8314
I opened PR on `react-navigation`.

**Comment by benevbright** [comment]
The PR was merged but reverted because it made a weird problem on Android. 
I opened PR again. https://github.com/react-navigation/react-navigation/pull/8317

**Comment by benevbright** [comment]
@react-navigation/stack@5.4.1 including the fix is released.
Let me do my side this weekend.

**Comment by benevbright** [comment]
No need work from my side. It's fixed.

**Comment by DragonBoyX** [comment]
Just upgraded to @react-navigation/stack@5.4.1 and it's Flawless! Thanks, @benevbright .
