### ISSUE TITLE
Hide both extraHeader and Header

### ISSUE THREAD

**Issue by vforvasile** [benevbright/react-navigation-collapsible#139]
Hey @benevbright! Thanks for keeping the library alive!

Quick question: is there a way to hide both extraHeader and navigation Header onScroll?

I tried some workarounds but I ended up messing the navigation Stack.

Any suggestions?

**Comment by benevbright** [comment]
I can't think of a solution. 
Maybe you can use `customHeader`. Sorry for the late reply.
