### ISSUE TITLE
Error when elevation is not supplied

### ISSUE THREAD

**Issue by isilher** [benevbright/react-navigation-collapsible#144]
## Information

- react-native version: 0.62.2
- react-navigation version: 5.6.1 (native), 5.5.1 (stack), 5.5.2 (bottom-tabs)
- react-navigation-collapsible version: 5.6.2
- Platform (iOS/Android): iOS
- react-native init or Expo: init

## Detail

When applying the first example from the README, removing the `elevation` property from the `createCollapsibleStack` call causes an exception:

> Invariant Violation: [567,"RCTView",21,{"position":"absolute","width":"100%","height":"100%","backgroundColor":4294967295,"shadowOpacity":"<<NaN>>","shadowRadius":"<<NaN>>","shadowOffset":{"height":"<<NaN>>","width":"<<NaN>>"}}] is not usable as a native method argument

**Comment by benevbright** [comment]
Thanks. It's fixed in `v5.6.3`
