### ISSUE TITLE
Invariant Violation Located in CollapsedHeaderBackground.js

### ISSUE THREAD

**Issue by DragonBoyX** [benevbright/react-navigation-collapsible#146]
## Information
- react-navigation-collapsible version: ^5.6.1
- Platform (iOS/Android): iOS 11
- react-native init or Expo: ~37.0.3

## Detail
I guess this error has occurred after the fix that was given in reference to this issue -
[Ghost Click on headerRight Stack Navigator #135](https://github.com/benevbright/react-navigation-collapsible/issues/135)

- Now the **Problem Occurs** on iOS 11 onwards

- **Works fine** with Android & older iOS versions

## Refer to the image attached below

![WhatsApp Image 2020-07-05 at 12 34 07 PM](https://user-images.githubusercontent.com/19872717/86528195-61fb9800-bec3-11ea-99d7-dc5801f4c45a.jpeg)

## Help 🤔
The problem is solved when I remove the collapsible functionality. It occurs only with the collapsible.
I hope we can overcome this issue too?

**Comment by benevbright** [comment]
https://github.com/benevbright/react-navigation-collapsible/issues/144
Maybe this one? 
Could you try 5.6.3?

**Comment by DragonBoyX** [comment]
@benevbright 

## A new error is thrown on Update to ^5.6.3
- react-navigation-collapsible version: **^5.6.3 (UPDATED)**
- Platform (iOS/Android): iOS 11
- react-native init or Expo: ~37.0.3

## Issue Screenshot
![WhatsApp Image 2020-07-05 at 3 10 56 PM](https://user-images.githubusercontent.com/19872717/86531962-85ced600-bee3-11ea-8c73-0931e672e67b.jpeg)

**Comment by benevbright** [comment]
Thanks for the additional info. 
Could you reproduce it with `/example`?
Or could you guide me with example codes on how to reproduce?
