### ISSUE TITLE
CollapsibleStackSub

### ISSUE THREAD

**Issue by Ankit-96** [benevbright/react-navigation-collapsible#150]
Trying to implement CollapsibleStackSub for hiding searchBar and actions on the basis of scrolling Flatlist.
Instead on using this my searchBar is completely gone and there's no action I can see while scrolling too (the list renders though). For the reference I have attached screenshots of both the cases..
@benevbright  Could you please help me out on this ??
![Without CollapsableStackSub](https://user-images.githubusercontent.com/18561772/88254130-d57a1380-ccd1-11ea-934e-8b0f86538dfc.png)
![With CollapsableStackSub](https://user-images.githubusercontent.com/18561772/88254138-dca12180-ccd1-11ea-95ca-952e0349bb51.png)

**Comment by benevbright** [comment]
The first screenshot is without the library and the second one is with it?
Could you share your code? And may I suggest to try to run the example of this library?
