### ISSUE TITLE
Getting "Warning: Cannot update a component from inside the function body of a different component." after upgrading to react v.16.13.1

### ISSUE THREAD

**Issue by aquile** [benevbright/react-navigation-collapsible#151]
## Information
- react-native version: 0.63.2
- react-navigation version: 5.4.2
- react-navigation-collapsible version: 5.6.1
- Platform (iOS/Android): iOS
- react-native init or Expo: react-native init 

## Detail
I get error "Warning: Cannot update a component from inside the function body of a different component." when calling  createCollapsibleStackSub() inside <FEStack.Navigator /> 

<img width="828" alt="Screenshot 2020-07-29 at 17 07 08" src="https://user-images.githubusercontent.com/11807795/88810380-f3f27a00-d1bd-11ea-9906-873063d228b3.png">

my code:
`
function TabsScreen({ navigation }) {
  return (
    <FEStack.Navigator>
      {
       createCollapsibleStackSub(
        <FEStack.Screen
          name={sceneKeys.myScreen}
          component={MyScreen}
        />)
       }
    </FEStack.Navigator>
  );
}
`

Notice, that error disappear when I remov createCollapsibleStackSub() 

Might be related to https://github.com/facebook/react/issues/18178 and

**Comment by benevbright** [comment]
@aquile Hi, thanks for your issue. 
My first assumption after looking at the error message and the linked issue in `react` is that this library could have been built in the wrong way and it may not be very easy to resolve. 
I'll take a look when I get a chance.

**Comment by shaneboyar** [comment]
![image](https://user-images.githubusercontent.com/7648555/93500622-56c0e180-f8e2-11ea-97d8-ea509da6de23.png)

**Comment by benevbright** [comment]
I'm moving the core logic to hooks. It may take time. 

Your reviews would be appreciated. Thanks!
https://github.com/benevbright/react-navigation-collapsible/pull/155 (WIP)

**Comment by ozerty** [comment]
Great idea !
I will review you PR and share feedback.
