### ISSUE TITLE
Custom Header Component Not Collapsed

### ISSUE THREAD

**Issue by tayguohong** [benevbright/react-navigation-collapsible#153]
Hi, I have a header with custom navigationOptions component. I am able to make header collapsed, however, its component is  not collapsed. Am I missing something?

![ezgif-4-412adfbd77b9](https://user-images.githubusercontent.com/57252173/93418074-237b5400-f8dc-11ea-8403-9175c754aa13.gif)

**Comment by benevbright** [comment]
Hi, can you check if you can reproduce the problem with the `/example` in the library?
