### ISSUE TITLE
Meteria top taps not working with react-navigation-collapsible

### ISSUE THREAD

**Issue by alejandro4k** [benevbright/react-navigation-collapsible#154]
Hi, i try to use this 2 libraries but 
I still can't figure out how to make it work, the thing is that the header is over the material top taps and i try all but i still whit this problem and header does not collapse, here is my code:

`import React, {Component} from 'react';
import {
  Animated,
  Dimensions,
  Platform,
  Text,
  View,
  TouchableOpacity,
} from 'react-native';

import {NavigationContainer} from '@react-navigation/native';
import {
  createStackNavigator,
  StackNavigationProp,
} from '@react-navigation/stack';
import {
  createCollapsibleStack,
  // disableExpoTranslucentStatusBar,
  useCollapsibleStack,
} from 'react-navigation-collapsible';
import {createMaterialTopTabNavigator} from '@react-navigation/material-top-tabs';

const data = [];
for (let i = 0; i < 100; i++) {
  data.push(i);
}
const Header = ({}) => {
  return (
    <Animated.View style={{backgroundColor: 'white', height: 50}}>
      <Text style={{color: '#079992', fontSize: 17, alignSelf: 'center'}}>
        HEADER COLLAPSIBLE
      </Text>
    </Animated.View>
  );
};
function NotificationsScreen() {
  return (
    <View style={{flex: 1, justifyContent: 'center', alignItems: 'center'}}>
      <Text>Notifications!</Text>
    </View>
  );
}

function ProfileScreen() {
  return (
    <View style={{flex: 1, justifyContent: 'center', alignItems: 'center'}}>
      <Text>Profile!</Text>
    </View>
  );
}
const FeedScreen = () => {
  const {
    onScroll,
    containerPaddingTop,
    scrollIndicatorInsetTop,
  } = useCollapsibleStack();

  return (
    <Animated.FlatList
      data={data}
      onScroll={onScroll}
      contentContainerStyle={{paddingTop: containerPaddingTop}}
      scrollIndicatorInsets={{top: scrollIndicatorInsetTop}}
      renderItem={({item}) => (
        <TouchableOpacity
          style={{
            width: '100%',
            height: 50,
            alignItems: 'center',
            justifyContent: 'center',
            borderBottomColor: 'gray',
            borderBottomWidth: 1,
          }}>
          <Text
            style={{
              fontSize: 22,
            }}>
            {item}
          </Text>
        </TouchableOpacity>
      )}
      keyExtractor={(item) => item.toString()}
    />
  );
};
const Tab = createMaterialTopTabNavigator();
const Stack = createStackNavigator();

const HomeStack = () => {
  return (
    <Stack.Navigator>
      <Stack.Screen name="Home" component={TapScreens} />
    </Stack.Navigator>
  );
};

const TapScreens = ({route, navigation}) => {
  return (
    <Tab.Navigator
      initialRouteName="Feed"
      tabBarOptions={{
        labelStyle: {fontSize: 12},
      }}>
      <Tab.Screen
        name="Feed"
        component={FeedScreen}
        options={{tabBarLabel: 'Home'}}
      />
      <Tab.Screen
        name="Notifications"
        component={NotificationsScreen}
        options={{tabBarLabel: 'Updates'}}
      />
      <Tab.Screen
        name="Profile"
        component={ProfileScreen}
        options={{tabBarLabel: 'Profile'}}
      />
    </Tab.Navigator>
  );
};

export default function App() {
  return (
    <NavigationContainer>
      <Stack.Navigator>
        {createCollapsibleStack(
          <Stack.Screen
            name="Home"
            component={TapScreens}
            options={{
              headerStyle: {backgroundColor: 'green'},
              headerTintColor: 'white',
              title: 'Regular Header 2',
            }}
            />,{
              collapsedColor:'red'
            }
        )}

      </Stack.Navigator>
    </NavigationContainer>
  );
}
`
PLEASE HELP ME, THANKS!

**Comment by benevbright** [comment]
Hi, sorry for the late reply. This library doesn't support tab navigator.
