### ISSUE TITLE
options.headerStyle are not applied anymore

### ISSUE THREAD

**Issue by rickiesmooth** [benevbright/react-navigation-collapsible#156]
## Information
- react-native version: 0.63.2
- react-navigation version: 
   - "@react-navigation/bottom-tabs": "^5.8.0",
   - "@react-navigation/native": "^5.7.3",
   - "@react-navigation/stack": "^5.9.2",
- react-navigation-collapsible version: 5.7.0
- Platform (iOS/Android): iOS
- react-native init or Expo: Expo

## Detail
Since I've updated to 5.7.0 I don't see the `headerStyle`'s being applied anymore

```
      <CollectionStack.Screen
        name="CollectionScreen"
        component={CollectionScreen}
        options={{
          headerStyle: {
            height: 120,
            backgroundColor,
            borderColor: 'red',
            borderWidth: 2,
          },
          headerTitle: (props) => (
            <HeaderBar
              title="Title"
              hasBackButton={false}
              {...props}
            />
          ),
        }}
      />
```

**Comment by rickiesmooth** [comment]
oops, should've read the docs..now I pass the options to the hook and it works

**Comment by benevbright** [comment]
Hi, there was another breaking change today. I apologize. 
https://github.com/benevbright/react-navigation-collapsible/pull/160
