### ISSUE TITLE
Please bump to version 6

### ISSUE THREAD

**Issue by benvds** [benevbright/react-navigation-collapsible#163]
Updating now is confusing because version 5.7 introduced breaking changes for existing code. This means it's a major change according to [semver](https://semver.org/):

> MAJOR version when you make incompatible API changes,

As [npm uses semver](https://docs.npmjs.com/about-semantic-versioning) I suggest bumping to version 6.0.0.

**Comment by benevbright** [comment]
Hi, It's a very valid point. But I had to go with the minor change because I wanted to imply that v5 of this library is relying on the `react-navigation` v5.

**Comment by benvds** [comment]
Ah I never thought about that. Can't you mention it on the readme and add it as a [peer dependency](https://nodejs.org/en/blog/npm/peer-dependencies/)?

Great library by the way, this is making my app a lot more user friendly.

**Comment by benevbright** [comment]
Hm.... You're right... I guess I weighted too much on that idea of the implication. 
I think providing a specific version in the peer-dependency must have been the right approach. 
I know it's too late but we can go with v6. What do you think? Thanks for the heads-up btw.
