### ISSUE TITLE
Support with react-native-maps

### ISSUE THREAD

**Issue by MAgungHKM** [benevbright/react-navigation-collapsible#171]
Is there any way to make this module works with react-native-maps?

**Comment by benevbright** [comment]
I've never tried it. How does it look like? Do you have GIF?

**Comment by MAgungHKM** [comment]
I haven't tried it myself, more like I don't understand as to what am I suppose to do. I only managed to use this module with `<Animated.ScrollView>` up to this date. 

What I do understand is, I probably need to use custom Listener by using react-native-maps `onRegionChange` or `onPanDrag` events and try to integrate it with `onScroll` or `onScrollWithListener` events from this module. I might try to play around with it for the time being.

**Comment by benevbright** [comment]
I see. 
I can't really tell now if it's gonna work.

I would just remove the header of the navigation completely on that screen with a map. :) haha 
But it would be up to your use case, of course.

**Comment by MAgungHKM** [comment]
in most cases, I would agree with you, but since I'm currently dealing with a lot of screen and drawer navigation is probably the best way to go, I do need that header as an ease of access to open the drawer.

but oh well, the users doesn't really mind it so I guest it's fine *shrug*

**Comment by benevbright** [comment]
@MAgungHKM Yeah, you can also use the custom button with navigation action.

**Comment by MAgungHKM** [comment]
that's also true
