### ISSUE TITLE
iOS 11 style big header

### ISSUE THREAD

**Issue by benevbright** [benevbright/react-navigation-collapsible#18]
https://github.com/react-navigation/react-navigation/issues/2749

Many people want the iOS11 style header. 
But when you look at carefully, you will notice its transition is complicated.
And scroll action that hiding and showing search bar and the header is working so naturally.

**Comment by simb4** [comment]
I've done kind of large title behaviour in project. Here the way it is possible to do https://medium.com/appandflow/react-native-scrollview-animated-header-10a18cb9469e
See this comment to implement it with react-navigation
https://github.com/react-navigation/react-navigation/issues/480#issuecomment-284502212

**Comment by enagorny** [comment]
There is also library https://github.com/zobeirhamid/react-native-scrollable-navigation-bar but it's poorly documented

**Comment by benevbright** [comment]
@enagorny This one looks really good. I will check it out too! Thanks.

**Comment by benevbright** [comment]
react-navigation@next (v5) has this. 👏
https://reactnavigation.org/blog/2019/10/17/react-navigation-native.html

**Comment by caiobiodere** [comment]
@benevbright do you know if they have removed this from the v5 last version?

**Comment by benevbright** [comment]
@caiobiodere yeap. I guess so.
