### ISSUE TITLE
v6.0.0 default project broken

### ISSUE THREAD

**Issue by ryanoillataguerre** [benevbright/react-navigation-collapsible#192]
## Information
- react-native version: 39.0.4
- react-navigation version: 5.7.4
- react-navigation-collapsible version: 5.8.0
- Platform (iOS/Android): iOS
- react-native init or Expo: Expo

## Detail

I have been having trouble getting this package to work in my app, which is an expo app just created a few days ago. I can get the app working (sometimes) while using `react-navigation-collapsible`, but have run into this issue on there before as well. That's using the most recent version of above packages, and v6.0.0 of this lib.

However, this is in the default Expo snack, which when running on my devices (iPhone 11 Pro Max and M1 Macbook Pro) errors on start with the following: `Tried to register two views with the same name RNCSafeAreaProvider`

![IMG_4CB046D33C80-1](https://user-images.githubusercontent.com/28904005/128646737-3c5e8df4-e584-4957-a3cd-e596586824cf.jpeg)

Wondering if someone could confirm whether this is the case on their devices, whether it's the case with v6.0.0, or just with v5. Marking as bug since it's using all default combinations of versions.

Thank you!

**Comment by benevbright** [comment]
react-navigation-collapsible 6.0.0 requires v6 `react-navigation` as a peer dependency. check here. https://github.com/benevbright/react-navigation-collapsible/blob/cec99a4852301ef2aef121bd09816863c759c5ea/package.json#L35

I just tested with Expo snack and it seems fine https://snack.expo.io/@benevbright/react-navigation-collapsible

Could you check again?
