### ISSUE TITLE
Collapse as soon as scrolling starts

### ISSUE THREAD

**Issue by cheymonty** [benevbright/react-navigation-collapsible#196]
I want the header to start collapsing right when the user starts scrolling instead of getting to a certain position. Is that possible?

**Comment by benevbright** [comment]
It has exported function `setSafeBounceHeight` for that. But unfortunately, it's really not compatible with iOS's bouncing effect. You can try it out but it wouldn't be working well.

**Comment by cheymonty** [comment]
thanks I found that, if I set bounces={false} it works well. Thank you
