### ISSUE TITLE
containerPaddingTop is not working properly for expo project, with temporary fix

### ISSUE THREAD

**Issue by lclrobert2020** [benevbright/react-navigation-collapsible#199]
## Information
- react-native version: expo version 42,
- react-navigation version:  same as expo example
- react-navigation-collapsible version:  same as expo example
- Platform (iOS/Android): android
- react-native init or Expo: expo
## Detail
Sorry for my informal report, I am still learning RN.
The containerPaddingTop is not working properly for the expo project,
for the default header, the top part of the flatlist goes behind the header as the containerPaddingTop  doesn't include the statusBarHeight for expo project
The bug occurs in the utils.js, the function getStatusBarHeight:
```
var getStatusBarHeight = function (isLandscape) {
    if (Platform.OS === 'ios') {
        if (isLandscape)
            return 0;
        return isIphoneX() ? 44 : 20;
    }
    else if (Platform.OS === 'android') {
        // @ts-ignore
        return global.Expo && !disabledExpoTranslucentStatusBar
            ? StatusBar.currentHeight
            : 0;
    }
    else
        return 0;
};
```
On inspection, the global.Expo is false even when I am using expo, the temp fix is to assign true to global.Expo in the App.tsx or in the entry point of the app if you are USING EXPO
```
global.Expo = true
```

**Comment by benevbright** [comment]
fixed in v6.2.0. Thanks a lot for the detailed report! (and the workaround)
