### ISSUE TITLE
Extra space when using DrawerNavigator

### ISSUE THREAD

**Issue by karelnet** [benevbright/react-navigation-collapsible#20]
Hi,

Great job, this collapsible feature works well.
I have an issue though when inserting a drawer navigator in between StackNavigator and MaterialTabNavigator, just like this : 
https://readybytes.in/blog/how-to-integrate-tabs-navigation-drawer-navigation-and-stack-navigation-together-in-react-navigation-v2

When making MaterialTabNavigator collapsible, there is an extra space between header and tabs (see screenshot).
If I remove collapsible options, it works well (but no collapsing of course)

Thanks

![extraspace](https://user-images.githubusercontent.com/18073828/45017748-bc5a1200-b028-11e8-900d-5e2fbbc1fb86.jpg)

**Comment by benevbright** [comment]
Hi, @karelnet .
Thanks very much for your issue.

I think it's a general mistake when people use drawerNavigator. 
If you have any change to look at several major apps, Drawer is always on the most top layer. (So user can't touch any button  when it's open but you can touch only buttons in the drawer)
But in the code at the link, Drawer is under StackNavigator as a child.
I can say it's not a good practice.

**Comment by karelnet** [comment]
Thank you for your quick reply.
You are absolutely right. I changed this and set DrawerNavigator at the most top layer and everything is fine.
👍 🥇

**Comment by karelnet** [comment]
By the way...

I have another problem. I have : 
- DrawerNavigator (default DrawerItems)
- StackNavigator
- Tabs with collapsible

With Drawer Navigator when I switch from Tabbed screen to a screen with no tabs (and nothing collapsible) then get back to collapsible tabs, it is not collapsible anymore.

(I hope this is clear...)

**Comment by benevbright** [comment]
Is there any chance you didn't add this line?

https://github.com/benevbright/react-navigation-collapsible/blob/d747e01f07f9f22b77419fe67dfbd60d4dcc892f/example/src/FlatListScreen.js#L57

I will look at this issue as well on my side.
Thanks.

**Comment by karelnet** [comment]
This line is in the code

**Comment by benevbright** [comment]
Hi, @karelnet 
I was able to reproduce it and fixed it. 
Please check the 0.2.16 version on npm.

Thanks again for your issue.
