### ISSUE TITLE
Header is not collapsible, if stack navigator is inside bottom tab navigator

### ISSUE THREAD

**Issue by Strate** [benevbright/react-navigation-collapsible#39]
I can't get to work collapsible header, if stack navigator it located inside bottom tab navigator.

**Comment by Strate** [comment]
Sorry for this, I'll check it more accurately

**Comment by benevbright** [comment]
Thanks for your issue. 
Yes. Anytime!

**Comment by jbtobar** [comment]
Has this been solved? Having the same issue.
