### ISSUE TITLE
Enabling state persistence of react-navigation break collapsible headers.

### ISSUE THREAD

**Issue by Strate** [benevbright/react-navigation-collapsible#40]
Steps for reproduction:

1. Go to example dir
2. Change `<StackNavigator key='navigator'/>,` to `<StackNavigator key='navigator' persistenceKey="navigator" />,`
3. Open app, go to any example screen, for example first one.
4. Close and re-open app.

Application launched on previously opened screen, but header is not collapsible.

P.S. Thank you for this awesome library :)

**Comment by benevbright** [comment]
Thanks for your issue! @Strate 
I tested it as you said and I was able to reproduce it. Thanks for your information.
Are you using `persistenceKey` in production or just for debug?

**Comment by Strate** [comment]
@benevbright as for now, I don't use it (because it breaks this awesome library). But it was tricky to find why library don't works. It would be great to notice about it in README

**Comment by benevbright** [comment]
It's really good to hear. I know it's really limited and has many things to be improved. 
Yes, I will note it in README and look into it.

**Comment by summerkiflain** [comment]
Is there any workaround for this? (making collapsible header work with state persistence), even though I am using it only in dev mode, but I would like it see it work in dev mode also, switching between dev and prod mode seems buggy for me on current expo version (2.18.5).
