### ISSUE TITLE
collapsing nested tabnavigator headers does not work with react-navigation v1

### ISSUE THREAD

**Issue by haseebnaseem** [benevbright/react-navigation-collapsible#41]
Hi, My navigation configuration is deeply nested which is maybe causing trouble to implement collapsible headers. 

react-navigation version:1.5.11
react-navigation-collapsible:0.2.18

Does the library work with react-navigation v1 ? 

Can provide with the configs if it is intended to work with react-navigation v1

**Comment by benevbright** [comment]
Hi, I've not tried with v1 yet. 
And could you give me some hierarchy of your navigation?

**Comment by haseebnaseem** [comment]
It is something like this 
```
StackNavigatorA
    TabNavigatorA
        TabNavigatorB
        StackNavigatorB
        TabNavigatorC
        StackNavigatorC
```

**Comment by benevbright** [comment]
Hi, I tried to get it worked with v1.
Unfortunately, it's not working properly and performance is not good with this module.
I don't think I could work on it. Sorry about it.

I tested it a bit on this branch.
https://github.com/benevbright/react-navigation-collapsible/tree/with-navigation-v1
