### ISSUE TITLE
Possible to combine extra header with tabs? 

### ISSUE THREAD

**Issue by connormg** [benevbright/react-navigation-collapsible#42]
Is it possible to use this to have an extra header with a collapsing image/component above it? 

![screen shot 2018-10-19 at 8 22 15 am](https://user-images.githubusercontent.com/36305743/47220737-3f84bc80-d378-11e8-8d51-c65357ae55af.png)

Pretty much the image on the left, but instead of just a title, it would be a full component. I have tried many approaches but cannot seem to get it right.

**Comment by benevbright** [comment]
Can you explain, what could be improved or you expected more and it didn't on ImageHeader(the one on the left) of this module?

**Comment by connormg** [comment]
@benevbright  - When I apply a header, following the image example, that header will always sit on top of the tab navigator. The tab navigator is hidden behind the image, until I scroll all the way down and then it will display.

For more clarification of what I am looking for, the functionality is similar to what you would find on a Facebook group page. Collapsing header with a tab navigator below it. 

![screenshot_20181019-083928](https://user-images.githubusercontent.com/36305743/47221906-2598a900-d37b-11e8-90e0-5098607eb33f.png)

**Comment by benevbright** [comment]
Great. It's a good one.
Thanks for your information.
Let me see what I can do :)

**Comment by connormg** [comment]
@benevbright thank you!

**Comment by benevbright** [comment]
Hi, I updated the module. I appreciate your issue :)

Please look [example/src/AdvancedScreen.js](https://github.com/benevbright/react-navigation-collapsible/tree/master/example/src/AdvancedScreen.js) for your desired screen.

Or, you can also try [Expo Snack](https://snack.expo.io/@benevbright/react-navigation-collapsible).

NOTE: please update `react-navigation-collapsible` to 0.3.1.

**Comment by connormg** [comment]
@benevbright  - Thank you! I appreciate your time on this.

**Comment by alexpchin** [comment]
Hello! Where did this example go? This is exactly what I need for: https://github.com/benevbright/react-navigation-collapsible/issues/72
