### ISSUE TITLE
Same header state for all tabs?

### ISSUE THREAD

**Issue by emmx** [benevbright/react-navigation-collapsible#48]
I'm playing around with the Material Tab Screen example but I noticed it works slightly different than what I've seen in other apps using a similar approach.

Let me explain myself. Go to that screen and collapse the header in the first tab, then navigate to the second tab, the header will reappear. Go back an forth from tab 1 to tab 2 and back to reproduce.

Is there a way to disable that behavior? I expect the header's height/position to not depend on the selected tab at all, if it's collapsed for one tab it should remain collapsed for all of them.

**Comment by benevbright** [comment]
Hi, Thanks for your issue. 
I got what you're saying. But if you look Youtube app, it works as same as this module. 
Can you give me an example of one of a major app that works that way that you say?

**Comment by emmx** [comment]
On YouTube (channel page) I don't see the behavior of this lib, instead I see the one I described.

It seems that when the tab is first opened it does reset the state of the header, but that only happens the first time. After that, going back and forth doesn't affect the header at all for me.

I'll try to make a video showing this but I checked in both iOS and Android. Also Facebook (group's page) works in a similar way.

**Comment by emmx** [comment]
![46370592_936169486771295_8060440509669179392_n](https://user-images.githubusercontent.com/1238560/48674909-67f70680-eb30-11e8-903f-c78c17a46f4e.gif)

**Comment by benevbright** [comment]
Hey, @emmx I'm sorry. Somehow, I was confused with BottomTab.

![nov-18-2018 5-54-46 pm](https://user-images.githubusercontent.com/916690/48675613-43fcea80-eb5b-11e8-8614-03da5b8c6fd6.gif)
Bottom tab works like what I said, but Top tab works normally like what you said. 

Hm... Good point.. Thanks very your detail and GIF! Let me see if there is something I can do about it.

**Comment by benevbright** [comment]
One workaround is using your own TopTab Component(or third party TopTab component) such as shown in `Advanced Screen` in the example.
I know this is not an ideal though.

![demo2](https://user-images.githubusercontent.com/916690/48675751-347ea100-eb5d-11e8-92a9-cc39901a2396.gif)
(Advanced screen in example of this module)

**Comment by emmx** [comment]
I've put together a snack example that works almost as described. The code is similar to what you do in this lib so I hope you can add support for this pattern too with minor changes.

There are two errors I couldn't fix yet and those are:

- Shaking behavior while scrolling. This happens on Android only so no idea how to fix it
- If you collapse the header on one tab and go to another the content has a blank space/margin at the top. This happens on both Android and iOS

Did you have any of these problems?

https://snack.expo.io/@mattx/collapsible-header-tabs

**Comment by emmx** [comment]
Hi. I've been discussing this with JanPeter from [1], he also implemented a similar pattern though it was just an answer for a StackOverflow question. Maybe you should check his code. It has other problems (check issue #4 on his repository) but it's a good starting point.

As I mentioned there, I believe we should aim to do something like follows:

```js
import Header from './Header'
import Feed from './Feed'
import Info from './Info'

// Create your top tab navigator
const Navigator = createMaterialTopTabNavigator({Feed, Info}, {...})

// Here Navigator doesn't have to be or extend a react-navigator, it could be any component, even a simple ScrollView or FlatList should work
const Screen = createCollapsibleHeader(Header, Navigator, {...})

export default Screen
```

Recently I found [2] and [3], which are not libs but articles showing how to achieve similar patterns, they require a great deal of work to adapt it to your particular needs. In particular [3] is very cool but doesn't support swiping, however it supports "snaps" (don't know how it's really called, but the point is if you let go the scrolling it would either complete the animation or go back to its original position depending on whether you reached a certain point).

Hope it helps you!

[1] https://github.com/JanPeter/RN-NavigationHeaderAnimation
[2] https://codeburst.io/react-native-parallax-scroll-with-tabs-721feec463c5
[3] https://blog.expo.io/implementation-complex-animation-in-react-native-by-example-search-bar-with-tab-view-and-collapsing-68bb43be2dcb

**Comment by Jalson1982** [comment]
any progress on this?

**Comment by benevbright** [comment]
Hi, I had been busy for work. Sorry about it. 
I'm working on it this issue now and V3. But I'm having trouble to share `Animated` from multiple sources(in this case, Tab children). 

![jan-06-2019 10-30-43 pm](https://user-images.githubusercontent.com/916690/50741816-118a7800-1203-11e9-98b5-69dd6a31820f.gif)

**Comment by 0x01001** [comment]
> Hi, I had been busy for work. Sorry about it.
> I'm working on this issue now and V3. But I'm having trouble to figure out how to share an`Animated` from multiple scroll sources(in this case, from Tab children).
> 
> ![jan-06-2019 10-30-43 pm](https://user-images.githubusercontent.com/916690/50741816-118a7800-1203-11e9-98b5-69dd6a31820f.gif)

thank for awesome lib, any update for this issue?

**Comment by tyuwan** [comment]
This actually solved my issue with Animated.add().

https://stackoverflow.com/questions/46980077/animating-a-single-view-based-on-multiple-scrollviews

**Comment by benevbright** [comment]
@tyuwan Thanks very much and your link.
Yes, I'm actually solving it with `Animated.add` :)
I think I could come back with a solution soon.

**Comment by benevbright** [comment]
Hi, I appreciate your comments.
It's about to be released.
#50

**Comment by KingAmo** [comment]
> @tyuwan Thanks very much and your link.
> Yes, I'm actually solving it with `Animated.add` :)
> I think I could come back with a solution soon.

hi, @benevbright ， i do not see any `Animated.add` code in this repo, could you please explain how you did this?

**Comment by benevbright** [comment]
@KingAmo Hey. It was fixed once. But I dropped the material tab support in v5 version.

**Comment by KingAmo** [comment]
@benevbright so is there a way to have collapsible header with tabs ? i have struggled for days

**Comment by benevbright** [comment]
@KingAmo with material tab? Sadly no, with this library.

**Comment by KingAmo** [comment]
so could i use https://github.com/react-native-community/react-native-tab-view instead ?

**Comment by benevbright** [comment]
@KingAmo 
I don’t think so. Because you will meet this RN bug anyway. https://github.com/facebook/react-native/issues/21801
That’s why I had to drop the support.

**Comment by KingAmo** [comment]
@benevbright thanks a lot !

**Comment by mehthabux** [comment]
https://github.com/Stormotion-Mobile/react-native-collapsing-tab-header
