### ISSUE TITLE
Support react-navigation v3

### ISSUE THREAD

**Issue by benevbright** [benevbright/react-navigation-collapsible#49]
We need to support react-navigation v3. 
But it's just released and it does not seem to be stable.

pre-release on npm: `react-navigation-collapsible@next`

**Comment by nonotest** [comment]
yep there seems to be some issues for example the header is missing some paddingHeight for me , like 20 and goes to the wrong spot all the time.
not exactly sure of where it comes from.. happy to have a look this weekend if no one does before

**Comment by nonotest** [comment]
i think we also need to remove the safeareaview included in this module

**Comment by benevbright** [comment]
Yes, I'm updating the work here https://github.com/benevbright/react-navigation-collapsible/pull/50.

**Comment by z98361** [comment]
when using collapsibleCustomHeader appear white background after header
scroll half:
![](https://i.imgur.com/kQnlKoW.png)
end scroll:
![](https://i.imgur.com/abBp3mS.png)

**Comment by benevbright** [comment]
Thanks very much. @z98361 
I'll look at it.

**Comment by paolospag** [comment]
Hi @benevbright,
first of all congratulations for your very useful module.

Any updates about RN 3.0 support? The latest version is still in alpha.

**Comment by benevbright** [comment]
Hi, I appreciate your comments. 
It's about to be released.
https://github.com/benevbright/react-navigation-collapsible/pull/50

**Comment by 0x01001** [comment]
> when using collapsibleCustomHeader appear white background after header
> react-navigation: v3.0.5
> react-navigation-collapsible: v3.0.0-alpha1
 
This issue is not fix

`class DefaultHeaderScreen extends Component{
  static navigationOptions = {
    // title: 'Default Header'
    header: (<View style={{height: 56, justifyContent: 'center', alignItems: 'center', backgroundColor:'green'}}><Text>Header</Text></View>)
  };
...`

[https://i.imgur.com/7oOuPUB.png](https://i.imgur.com/7oOuPUB.png)

**Comment by benevbright** [comment]
Hi, @0x01001 I appreciate your issue.

Unfortunately, the Custom component header is no longer supported on v3 of this module. It's making some problems especially in transition, and implementation of the Custom component header on `react-navigation` got worse than v2. I gave up with that, tbh.

**Comment by 0x01001** [comment]
> Hi, @0x01001 I appreciate your issue.
> 
> Unfortunately, the Custom component header is no longer supported on v3 of this module. It's making some problems especially in transition, and implementation of the Custom component header on `react-navigation` got worse than v2. I gave up with that, tbh.

Thanks for help quickly, fixed by using headerLeft or headerRight.
