### ISSUE TITLE
Is it possible to achieve this?

### ISSUE THREAD

**Issue by Jalson1982** [benevbright/react-navigation-collapsible#51]
Hello friend. At first I must say an awesome job you are doing ! I am trying to create this : https://i.stack.imgur.com/tW209.gif , I tried to do the same as material tab and have few issues. First one is that if I am on TAB1 and scroll, and switch to TAB2 with swipe header return down with some not smooth effect. But if I am on TAB1 and press TAB2 without swipping it works like charm and I can not see padding top ( that is issue nr 2) . Anyway if you have time to give some advice what would be best way to achieve it it would be great!

**Comment by Jalson1982** [comment]
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/35011526/48786198-9ae2fb00-ece6-11e8-8d40-6ce43a96083b.gif)

**Comment by benevbright** [comment]
Hi, Thanks for your issue!
Is there any chance you talking about the same issue with this one #48 ?

**Comment by Jalson1982** [comment]
Hmm for me it is not problem to header shows up , it would be nice to have same smooth effect as I have when press TAB , and when it is not smooth at all ...  look at gif i attach you can see that is much better when press tab then on swipe... 

![svid_20181120_170008_11](https://user-images.githubusercontent.com/35011526/48790641-1e551a00-ecf0-11e8-86ab-c5e674991758.gif)

**Comment by benevbright** [comment]
Hey, @Jalson1982 I really appreciate your GIF. I got what's the problem.
I'm going to think about this issue this weekend. Thanks again!

**Comment by Jalson1982** [comment]
Thx a lot mate. Also one question more. Can we use custom header and tabs? For example Header from native base component and tabs from react native tab view?

**Comment by benevbright** [comment]
Hi, I appreciate your comments.
It's about to be released.
#50
