### ISSUE TITLE
TypeError: TypeError: undefined is not an object (evaluating 'value.getValue')

### ISSUE THREAD

**Issue by 0x01001** [benevbright/react-navigation-collapsible#59]
In example if default show screen withCollapsible not MenuScreen (my app show withCollapsible in first screen) will get error below:
```
const routeConfig = { 
  S0_DefaultHeader: { screen: S0_DefaultHeader },
  S1_ExtraHeader: { screen: S1_ExtraHeader },
  S2_DefaultHeaderForTab: { screen: S2_DefaultHeaderForTab },
  S3_ExtraHeaderForTab: { screen: S3_ExtraHeaderForTab },
  DetailScreen: { screen: ContextScreen },
};
```
![screenshot_1548738543](https://user-images.githubusercontent.com/3379258/51885641-07513900-23bf-11e9-9c04-cee63d2a61c3.png)

thank you!

**Comment by benevbright** [comment]
Thanks @0x01001 !! 
It's fixed :)
