### ISSUE TITLE
Pull to refresh hides collapsible header

### ISSUE THREAD

**Issue by aryankonstant** [benevbright/react-navigation-collapsible#61]
Collapsible header works fine, but when I do pull to refresh on AnimatedList, it hides back and does not show until I normally scroll down the list and come back up. Anyone else facing this issue? Please help me with this.

**Comment by benevbright** [comment]
Hi, @aryankonstant 
I appreciate your issue. I tried a few approaches. 
Unfortunately, nothing makes it work. Let me get back to you later when I found a solution.

**Comment by wns3645** [comment]
Hi, I think it can be resolved by using [this PR](https://github.com/facebook/react-native/pull/24191) that I wrote in the `react-native` core repo. The PR has been merged but not released yet. So if you think it can resolve the issue you can apply it via `postinstall` script.

**Comment by benevbright** [comment]
@wns3645 Thanks very much for your information. 
I will try it once it's release.
