### ISSUE TITLE
Header box shadow?

### ISSUE THREAD

**Issue by kufii** [benevbright/react-navigation-collapsible#66]
I'd like to use a box shadow on the header much like how the default react-navigation header looks on android. Is there a way I can do this? styling the collapsiblecomponent doesn't help because while it looks fine when expanded, you lose the shadow when collapsed

**Comment by kufii** [comment]
Ok so I figured out the issue with the box shadow, the issue was I was styling the component itself vs using collapsibleBackgroundStyle.

I'm still having trouble with a related issue tho. On iOS, I want a hairline border at the bottom of the header. It looks exactly like how I want when fully extended, but when collapsed there is no border.

I'm using this for the style
```javascript
collapsibleBackgroundStyle: {
	height: 60,
	backgroundColor: '#fff',
	borderBottomColor: '#a7a7aa',
	borderBottomWidth: StyleSheet.hairlineWidth
}
```

here's some screenshots:

Extended:  
![image](https://user-images.githubusercontent.com/4913552/52171366-d27c1380-2729-11e9-9a44-dc7897b6fcc3.png)

Collapsed
![image](https://user-images.githubusercontent.com/4913552/52171370-e45db680-2729-11e9-8d39-a95738adc31a.png)

Notice how there's no border in the collapsed image

**Comment by benevbright** [comment]
I got your question. It's a really good case to know. 
I think what you can do is... keep `collapsibleBackgroundStyle.height` 60 and set your `collapsibleComponent`'s inline style height as 61 or 62.

**Comment by benevbright** [comment]
Or it could be relative with https://github.com/benevbright/react-navigation-collapsible/issues/63#issue-405106115 No.2 . Could you try this approach too?

**Comment by kufii** [comment]
yes, it seems like I would be able to use this solution provided I could disable the opacity.

I would say tho that I would still like the opacity of the contents to change, but have the container stay fully visible. IE if I had a search box within the extended header, the search box would disappear when collapsing, but the container would stay fully opaque

**Comment by benevbright** [comment]
Ok, you are absolutely correct. Please forget about what I said before.
How do you think we could improve this in a good way?
Bottom line is that we need to expand Extra component's height slightly like 1 or 2 pixels longer than collapsible height.
Maybe we can apply `paddingBottom` or `marginBottom` from `collapsibleBackgroundStyle`. `marginBottom` would make more sense though.

**Comment by kufii** [comment]
That was fast! Thanks a lot, this lib is fantastic
