### ISSUE TITLE
Can I use withCollapsibleForTab with react-native-tab-view?

### ISSUE THREAD

**Issue by Nikualla1** [benevbright/react-navigation-collapsible#74]

**Comment by benevbright** [comment]
`withCollapsibleForTab` is only working with `react-navigation`'s `MaterialTapNavigator`.

But `react-navigation` is using `react-native-tab-view` for Tabs.
https://github.com/react-navigation/react-navigation-tabs/blob/e23142ec736cf7516123e2f9ba96f102045aae85/package.json#L42

**Comment by Nikualla1** [comment]
I know, but I want to use dynamic Tabs which MaterialTopNavigator cannot provide as far as I know

**Comment by benevbright** [comment]
Ah, gotcha. Good to know.

If your custom tab navigator (I'm not sure if you've created your navigator) is shaped similar with MaterialTopNaviagtor, it would not complain I guess.

https://github.com/benevbright/react-navigation-collapsible/blob/8dc33e36b25ea71c2f9cd5f9b2d51895ccd88ffe/index.js#L328-L363

**Comment by Nikualla1** [comment]
Tried using it like:
export default withCollapsibleForTab(TabViewComponent, collapsibleParams) but didnt work...

**Comment by benevbright** [comment]
Yes, as I mentioned above, It should be your Navigator, not component.
