### ISSUE TITLE
Extra Header With Tab (e.g Facebook Group) customisation

### ISSUE THREAD

**Issue by Latgals** [benevbright/react-navigation-collapsible#75]
Hi!

Loved your component. I use it in Expo. But there are questions:

1. Is it possible to customize titles, for example, to add icons? I started trying to do it through a function, but an error occurred.

2. Is it possible to make TabBar above a photo? Then if you make a translucent background for the panel, it can be beautifully. I thought to do it through a negative marginTop, but the panel shifted under the photo.

3. For Extra Header With Tab (e.g. Facebook Group), if the list below is short, for example, 4-8 items, then it does not scroll. For small lists, ScrollView doesn't work here either. setSafeBounceHeight did not help. Maybe I did not use it correctly?

I think it will be useful to others.
Thank

**Comment by benevbright** [comment]
Thanks @Latgals 

1. You should be able to customize everyting. Could you share your code and `react-navigation` version?

2. I don't think I understand correctly. Do you mean making the header translucent?

3. Yes, it's the one of limitations. I would suggest putting some dummy view on the bottom.

**Comment by Albert0405** [comment]
Does the flicker/jumpy bug on Extra Header not yet fixed? Oh my god why react-native doesn't come up with a fix????

**Comment by Latgals** [comment]
@benevbright 

Clause 1 is fine. I understood everything myself. Thank you.
On point 2 I want something like in the picture.

![cat3](https://user-images.githubusercontent.com/44416239/55291331-23388180-53e6-11e9-9b5b-bf0f2e8b188f.png)

**Comment by benevbright** [comment]
@Latgals You meant Tabbar goes to top and Picture View is under the Tab?

Is that's what you meant, I doesn't sound something doable with this module. 😢

**Comment by Latgals** [comment]
Ok, then I will think up something else. :-) Thanks!

**Comment by Albert0405** [comment]
@Latgals  This is probably what you're looking at and it has no problem with Jumpy/Flickery Bug on Android

https://snack.expo.io/@satya164/collapsible-header-with-tabview

**Comment by Latgals** [comment]
@Albert0405, Thank you very much. This is similar to what i need.

**Comment by Albert0405** [comment]
becareful man, i just found out it has bug when you started scrolling on one tab then try to switch on other tab, the height of the header is somewhat buggy
