### ISSUE TITLE
performace

### ISSUE THREAD

**Issue by misaku** [benevbright/react-navigation-collapsible#76]
how can i do fix problem with performace?
when i use two tabs scroable the application is slow, not so much, but has a little problem.

**Comment by benevbright** [comment]
Thanks for your issue.
Could you get me have more idea, do you notice the bad performance when you open the screen, or when you scroll the scrollview?

**Comment by misaku** [comment]
when i open screen has a delay to open, a long time 3 seconds more or less, and touch tab has delay too, scroll no had problem work perfectly. just open page and touch tab.

**Comment by radetsky** [comment]
I would like to join to this issue. I have the same problems with performance. I have 1 stack navigator plus TopTabNavigator. When I open a screen with TopTabNavigator XCode tell me that memory usage is doubled and CPU usage so high. 

I did all things as shown in the example. 

1. export default withCollapsibleForTab(TabNavigator, { iOSCollapsedColor: 'transparent' });
2. export default connect(mapStateToProps, actions)(withCollapsibleForTabChild(TabChildScreen));

**Comment by benevbright** [comment]
resolved by #103
