### ISSUE TITLE
problem with slow tabs

### ISSUE THREAD

**Issue by misaku** [benevbright/react-navigation-collapsible#8]
This component woks very good, but i have one problme, my tabs is slow, i dont kwnow if other componnent is imcompatible withe this.. i would like help.

my package.json

> {
  "name": "AppChat",
  "version": "0.1.0",
  "private": true,
  "devDependencies": {
    "babel-preset-react-native-stage-0": "^1.0.1",
    "jest": "^23.5.0",
    "jest-react-native": "^18.0.0",
    "react-devtools": "^3.2.3",
    "react-test-renderer": "16.3.1",
    "remote-redux-devtools": "^0.5.13",
    "remotedev-server": "^0.2.5"
  },
  "scripts": {
    "start": "react-native start",
    "keystore-release": "keytool -genkey -v -keystore my-release-key.keystore -alias my-key-alias -keyalg RSA -keysize 2048 -validity 10000",
    "bundle-release-android": "react-native bundle --platform android --dev false --entry-file index.js --bundle-output android/app/src/main/assets/index.android.bundle --assets-dest android/app/src/main/res/",
    "bundle-release2-android": "react-native bundle --platform android --dev false --entry-file index.js --bundle-output android/app/build/intermediates/assets/release/index.android.bundle --assets-dest /android/app/build/intermediates/res/merged/release",
    "bundle-debug-android": "react-native bundle --platform android --dev true --entry-file index.js --bundle-output android/app/src/main/assets/index.android.bundle --assets-dest android/app/src/main/res/",
    "build-release-android": "cd android && gradlew assembleRelease",
    "build-debug-android": "cd android && gradlew assembleDebug",
    "android": "react-native run-android",
    "ios": "react-native run-ios",
    "test": "jest",
    "reset": "watchman watch-del-all && react-native start --reset-cache",
    "react-devtool": "react-devtools",
    "redux-devtool": "remotedev --hostname=localhost --port=8000 --injectserver=reactnative",
    "redux-devtool-revert": "remotedev --revert=reactnative"
  },
  "jest": {
    "preset": "react-native"
  },
  "dependencies": {
    "axios": "^0.18.0",
    "native-base": "^2.7.2",
    "react": "16.3.1",
    "react-native": "^0.55.4",
    "react-native-elements": "^1.0.0-beta5",
    "react-native-fbsdk": "^0.7.0",
    "react-native-firebase": "^4.3.8",
    "react-native-google-signin": "^1.0.0-rc3",
    "react-native-material-ui": "^1.30.1",
    "react-native-vector-icons": "^5.0.0",
    "react-navigation": "^2.11.2",
    "react-navigation-collapsible": "^0.2.12",
    "react-navigation-redux-helpers": "^2.0.5",
    "react-redux": "^5.0.7",
    "redux": "^4.0.0",
    "redux-thunk": "^2.3.0"
  }
}

My extruture of navigation:

> StackNavigator->DrawerNavigator->StackNavigator(Collapsible)->MaterialTopTabNavigator

**Comment by benevbright** [comment]
Hi, @misaku I really appreciate your posting. I will look this.

One more question, how many screens in your tabNavigator and every screen use Collapsible?

And it would be good if you tell me which OS you've seen this behavior.

**Comment by misaku** [comment]
Hi thanks.
1. two screens, and both use collapsible
2. is different kind of problem, first when I switch tab, aminamtion has delay or crashes, but sometimes it is a delayable, second delay is when I pause tab is too slow
3. Android 8.0

Thanks for your attention

**Comment by benevbright** [comment]
https://github.com/react-navigation/react-navigation/issues/739
(putting here as a reference)

**Comment by misaku** [comment]
yah, i try change all of my code, but nothing.
but when i remove collapible is ok. i think is a imcompatible with something, but i dont know

**Comment by benevbright** [comment]
@misaku Oh, OK. Thanks for more information. 
I put that link here as a reference to find the problem. 
Thanks.

**Comment by misaku** [comment]
@benevbright 
I discovered the error, as on my desktop it is windows I was using react-native 0.55.4 because the version 0.56 is not working on windows, strange that I tested the collapsible on it solo and it worked perfect, but I decided to install linux on my leptop and upgraded to react native 0.56 and apparently everything is ok, sorry for the inconvenience.

and again thank you for your attention

**Comment by benevbright** [comment]
Oh, @misaku That's a good new. Yes, I heard react-native 0.56 is not working on windows now some reason. 

Thanks for letting me know!
