### ISSUE TITLE
Example using StackNavigator

### ISSUE THREAD

**Issue by oreporan** [benevbright/react-navigation-collapsible#80]
Hey
Thanks for the library
I can't find an example using `StackNavigator`

My code looks like this:

```
const MainNavigator = StackNavigator(
    {
        SCREENA: {
            screen: FeedPage,
            navigationOptions: ({navigation}) => {
                ...
            },
        },
```
How can I wrap the HOC here?

**Comment by benevbright** [comment]
Hi, Would you check the `/example` forder? https://github.com/benevbright/react-navigation-collapsible/tree/master/example

It's using `StackNavigator` (please keep it in mind it's using `v3`)

**Comment by oreporan** [comment]
Thanks for the quick reply
Do you still support react-navigation 1.x ?

**Comment by benevbright** [comment]
I'm afraid to say 'no', it's only supporting react-navigation v3.

**Comment by oreporan** [comment]
ok thanks :)
