### ISSUE TITLE
Pass event with withCollapsibleForTab example

### ISSUE THREAD

**Issue by mopilo** [benevbright/react-navigation-collapsible#82]
I followed your example and I want to try something out, I want to call an event in the TopTabNavigator navigation options,
`  headerLeft: <Icon name='navicon' size={35} color='white' style={{padding: 10}} onPress={()=> this.props.go()}/>`

buh i get this error  Cannot read property 'go' of undefined.

```
const collapsibleParams = {
  collapsibleComponent: A,  //A is a Component
  collapsibleBackgroundStyle: {
    height: 150, 
    backgroundColor: '#333743'
  }
}
```

`export default connect(mapStateToProps, mapDispatchToProps)(withCollapsibleForTab(TopTabNavigator, collapsibleParams));`

**Comment by mopilo** [comment]
I was able to fix this.

**Comment by iamtb** [comment]
> I was able to fix this.

Hey bro. how to fix this ??
Please :((

**Comment by mopilo** [comment]
I Updated navigationOptions with setParams. 

<Button
    title="Update the title"
    onPress={() => this.props.navigation.setParams({otherParam: 'Updated!'})}
  />
