### ISSUE TITLE
How to fix header whn use marginTop Style

### ISSUE THREAD

**Issue by kajianseminarislamipadang** [benevbright/react-navigation-collapsible#83]
How to fix header when I use marginTop in headerStyle in react navigation like this...???

![Screenshot_20190727-095848](https://user-images.githubusercontent.com/51998757/61989277-e3616e00-b056-11e9-9627-6e42ae4b339d.png)

![Screenshot_20190727-095906](https://user-images.githubusercontent.com/51998757/61989269-d0e73480-b056-11e9-997d-8fcdaaa3dc99.png)

**Comment by benevbright** [comment]
Sorry, this seems to be hard to achieve.
