### ISSUE TITLE
Prevent Collapsing untill..

### ISSUE THREAD

**Issue by Albert0405** [benevbright/react-navigation-collapsible#84]
Hi, thank you for this library! I love it,

How could i prevent from immediately collapsing the header if the scroll is not yet at the top part of a particular tab? 

Let say, I'm swiping-up to close-collapse the header, then after reaching the bottom part, i swipe-down go to the top part of the current tab but I dont want the header to open-collapse yet NOT UNTILL the scroll reached the top part of that tab.

similar to this.... 
https://imgur.com/a/Nuf46xP

(on the second time he swipe to the lowest part of the current tab then he swipe bottom to scroll up the tab but the header remain closed until the scroll reaches the upper part of the tab, that's the only time the collapsing of header will take effect, how to achieve that using your library?)

**Comment by benevbright** [comment]
What you want is impossible with this library. Sorry about it.

https://github.com/benevbright/react-navigation-collapsible#api
You can use `setSafeBounceHeight` setting to set the height where it should start collapsing but not for un-collapsing.
