### ISSUE TITLE
can i use it with `react-native-web`

### ISSUE THREAD

**Issue by geminiyellow** [benevbright/react-navigation-collapsible#9]
hi @benevbright , thanks for your great work. 
i try to use it with rnw, but looks not good.

this lib give me a warning

```
Animated: `useNativeDriver` is not supported
```

and some error 

```
inputRange must be monotonically increasing ,NaN
```

**Comment by benevbright** [comment]
Hi, @geminiyellow What is rnw? Are you talking about react-native-windows? 
I never had a change to use it before. 

Can you please try to open the module file and set `useNativeDriver` to `false`? (node_modules/react-navigation-collapsible/index.js)

**Comment by geminiyellow** [comment]
hi @benevbright , thanks for your great work, but, oh yep, `rnw` not support `nativeDriver`

**Comment by benevbright** [comment]
@geminiyellow 

Hi, I've been looking this, but `react-navigation` seems like it's not supporting `react-native-web` well in its latest version. 

I want to know what version you're using for
- react-native
- react-navigation
- Is it expo or react-native init app?

I would be helpful!

**Comment by benevbright** [comment]
Hi, @geminiyellow 
I added some code for web platform specification, which disabled `nativeDriver` for web.

Can you try 0.2.15 version of this module?

**Comment by geminiyellow** [comment]
@benevbright thanks for your reply, 

all my libs version are latest,  and not use expo.

> Can you try 0.2.15 version of this module?

ok, i will try it.

**Comment by benevbright** [comment]
Thanks. 
You are using latest ‘react-navigation’ with rnw and it works?

**Comment by geminiyellow** [comment]
yes, they working.  but you need to add env var `__DEV__` when you run webpack dev server.

dont know why react-navigation may it as hard code.

```
    "react-navigation": "^2.12.0",
    "react-native-web": "^0.8.4",
```

**Comment by IDFC-DEV** [comment]
Is this resolved?? Im looking for same

**Comment by geminiyellow** [comment]
nope, but nobody care this.
