### ISSUE TITLE
Support react-navigation@next (v5)

### ISSUE THREAD

**Issue by benevbright** [benevbright/react-navigation-collapsible#94]

**Comment by KestasVenslauskas** [comment]
Does this even work with v4?

**Comment by benevbright** [comment]
@KestasVenslauskas  I recently updated the example with v4 and the latest RN it looks fine, except the RN bug. https://github.com/benevbright/react-navigation-collapsible/issues/62

**Comment by benevbright** [comment]
https://github.com/benevbright/react-navigation-collapsible/pull/103 (v5 support) is almost ready. 
You can try with `next`.
```
yarn add react-navigation-collapsible@next
```
docs for v5: https://github.com/benevbright/react-navigation-collapsible/tree/v5
