### ISSUE TITLE
Usage with react-native-tab-view

### ISSUE THREAD

**Issue by KestasVenslauskas** [benevbright/react-navigation-collapsible#96]
Would be great to get a working example with react-native-tab-view.
Which is the component that react-navigation-tabs uses. I wonder how to implement that.
I'm using it because I need dynamic tabs.

**Comment by benevbright** [comment]
You will get `translateY` in `this.props.collapsible` props when you use `withCollapsible`.

https://github.com/benevbright/react-navigation-collapsible#given-props

https://github.com/benevbright/react-navigation-collapsible/blob/9b6288f064d38b56f998765f829186606e94ea3c/example/src/S0_DefaultHeader.js#L48

So, I think you can translate the Y position of your Tab component with it.
