### ISSUE TITLE
TypeError:cannot read property of 'setParams' of undefined

### ISSUE THREAD

**Issue by anyway1919** [benevbright/react-navigation-collapsible#97]
when I run DefaultHeaderScreen.js ,I have encountered such a mistake：

TypeError:cannot read property of 'setParams' of undefined

This error is located at:
in_withCollapsible(at renderApplication.js:40)

**Comment by benevbright** [comment]
Hi, thanks. Do you get this error when you run the example?
And please give more info.

## Information
- react-native version: 
- react-navigation version: 
- react-navigation-collapsible version: 
- Platform (iOS/Android): 
- react-native init or Expo:

**Comment by anyway1919** [comment]
"react-native": "0.61.2"
 "react-navigation": "^4.0.10"
"react-navigation-collapsible": "^3.0.3"
Platform  Android

**Comment by benevbright** [comment]
Thanks. @anyway1919 

> react-native init or Expo:

This one too, please.

**Comment by anyway1919** [comment]
react-native init

**Comment by anyway1919** [comment]
Running the example you provided did not encounter the problem I described. I will confirm it tonight. If there is a detailed error message, I will email you. thank you


发件人: Bright Lee
发送时间: 2019年12月2日 15:55
收件人: benevbright/react-navigation-collapsible
抄送: anyway1919; Author
主题: Re: [benevbright/react-navigation-collapsible] TypeError:cannot readproperty of 'setParams' of undefined (#97)

Hi, thanks. Do you get this error when you run the example?
And please give more info.
Information
• react-native version:
• react-navigation version:
• react-navigation-collapsible version:
• Platform (iOS/Android):
• react-native init or Expo:

**Comment by benevbright** [comment]
Thanks. @anyway1919

**Comment by anyway1919** [comment]
Hello, I found the problem yesterday. What a stupid mistake I did not initialize the configuration when I used react-navigation! I am running OK now! But I would like to ask a new question, when using react-navigation if I use navigationOptions‘head ’instead of  'title', can I achieve this effect? Thank you for your warm answer yesterday






在 2019-12-02 20:53:09，"Bright Lee" <notifications@github.com> 写道：


Thanks. @anyway1919

**Comment by benevbright** [comment]
@anyway1919 
Hi, thanks again. I’m glad to hear it worked. 
Are you talking about a custom component for the header? If so, this module doesn’t support that case. Once it’s supported until v2 but not anymore.

**Comment by anyway1919** [comment]
Yes, I mean a custom hearder. Anyway, thank you for your answers and ideas
发件人: Bright Lee
发送时间: 2019年12月3日 17:28
收件人: benevbright/react-navigation-collapsible
抄送: anyway1919; Mention
主题: Re: [benevbright/react-navigation-collapsible] TypeError:cannot readproperty of 'setParams' of undefined (#97)

@anyway1919
Hi, thanks again. I’m glad to hear it worked.
Are you talking about a custom component for the header? If so, this module doesn’t support that case. Once it’s supported until v2 but not anymore.
