### ISSUE TITLE
Dynamically change iOSCollapsedColor

### ISSUE THREAD

**Issue by KestasVenslauskas** [benevbright/react-navigation-collapsible#98]
Is there a way to change the iOSCollapsedColor param? For example if user changes apps theme?

**Comment by benevbright** [comment]
Now, no.
It's related to this issue https://github.com/benevbright/react-navigation-collapsible/issues/71

I was planning this on the v5 release, though. PR will be very welcome. 🙏

**Comment by benevbright** [comment]
duplicated with #71
